install.packages("arules")
data()
book<-read.transactions("C:\\Users\\sivak\\Desktop\\Excel r assignments\\Association Rules\\book.csv",rm.duplicates = FALSE,cols = c(1:11))
book<-read.transactions("C:\\Users\\sivak\\Desktop\\Excel r assignments\\Association Rules\\book.csv")

library(arules)
library(readr)
movie<-read.csv(file.choose())
str(movie)
summary(movie)
class(movie)
library(arulesViz)
arules<-as.matrix(apriori(movie[,6:15], parameter = list(support=0.02, confidence=0.5, minlen=2)))
arule<-as.matrix(apriori(movie[,6:15], parameter = list(support=0.02, confidence=0.6, minlen=2)))
inspect(head(sort(arule,by="lift")))
plot(arule)
library(arulesViz)
plot(arule,method="grouped")
