library(rvest)
library(XML)
library(magrittr)
surl_1 <- "https://www.snapdeal.com/product/activa-sd75led3i6-80-cm-315/618953333749/reviews?page="
snapdeal_reviews <- NULL
for (i in 1:30){
  surl <- read_html(as.character(paste(surl_1,sep=as.character(i))))
  srev <- surl %>%
    html_nodes("#defaultReviewsCard p") %>%
    html_text()
  snapdeal_reviews <- c(snapdeal_reviews,srev)
}
write.table(snapdeal_reviews,"television.txt",row.names = FALSE)
getwd()
str(snapdeal_reviews)
View(snapdeal_reviews)
install.packages("tm")
library(tm)
x<-Corpus(VectorSource(snapdeal_reviews))
inspect(x[1])
x<-tm_map(x, function(x)iconv(enc2utf8(x),sub="byte"))
x1<-tm_map(x,tolower)
x1<-tm_map(x1,removePunctuation)
x1<-tm_map(x1, removeNumbers)
inspect(x1[1])
x1<-tm_map(x1, removeWords,stopwords("english"))
x1<-tm_map(x1,stripWhitespace)
tdm<-TermDocumentMatrix(x1)
tdm
dtm<-DocumentTermMatrix(x1)
tdm<-as.matrix(tdm)
tdm[1:20,1:20]
W <- rowSums(tdm)
w_sub<-subset(W, W>=30)
barplot(w_sub, las=2, col=rainbow(30))
x1<-tm_map(x1, removeWords,c("without", "also", "ago","date"))
x1<-tm_map(x1,stripWhitespace)
tdm<-TermDocumentMatrix(x1)
dtm<-DocumentTermMatrix(x1)
tdm<-as.matrix(tdm)
w<-rowSums(tdm)
w_sub<-subset(w,w>=30)
barplot(w_sub,las=2,col=rainbow(30))
install.packages("wordcloud")
library(wordcloud)
w_sub1<-sort(rowSums(tdm), decreasing = TRUE)
wordcloud(words = names(w_sub), freq = w_sub)
wordcloud(words = names(w_sub1), freq = w_sub1)
wordcloud(words=names(w_sub1),freq=w_sub1,random.order=F,colors=rainbow(30),scale=c(2,0.5),rot.per=0.4)))
wordcloud(words=names(w_sub1),freq = w_sub1,random.order = F, colors = rainbow(30),scale=c(2,0.5),rot.per = 0.4)
window()
install.packages("wordcloud2")
library(wordcloud2)
w1<-data.frame(names(w_sub),w_sub)
colnames(w1)<-c('word','freq')
wordcloud2(w1, size = 0.5,shape = 'circle')
wordcloud2(w1, size = 0.2, shape='rectangle')
w2<-data.frame(names(w_sub1),w_sub1)
colnames(w2)<-c('word','freq')
w2<-data.frame(names(w_sub1), w_sub1)
wordcloud2(w2, size=0.5, shape='reactangle')
